"""Bundle states.json and copy.json into one script the page can load.

The two JSON files stay the source of truth: the author edits copy.json, the
thresholds live in states.json, and this regenerates the bundle. Doing it this
way rather than fetching at runtime keeps the page synchronous, keeps every
request same-origin, and means a missing deck is a build error rather than a
blank screen in front of a reader.

    python3 tools/v3/build_deck.py
"""
import json, pathlib

root = pathlib.Path(__file__).resolve().parents[2]
states = json.loads((root / "sim/states.json").read_text())
copy = json.loads((root / "sim/copy.json").read_text())

out = root / "tool/v3/deck.js"
out.write_text(
    "/* Generated by tools/v3/build_deck.py — do not edit.\n"
    " * Source of truth: sim/states.json (thresholds) and sim/copy.json (prose).\n"
    " * Regenerate after either changes. */\n"
    "window.SIM_STATES = " + json.dumps(states, ensure_ascii=False, separators=(",", ":")) + ";\n"
    "window.SIM_COPY = " + json.dumps(copy, ensure_ascii=False, separators=(",", ":")) + ";\n"
)
written = len(copy["slots"])
filled = sum(1 for s in copy["slots"].values() if s["text"])
print(f"wrote {out.relative_to(root)}  ·  {written} slots, {filled} written, {written - filled} waiting")
